<?php
/**
 * @file
 * Implementation of hook_node_view_alter();
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\NodeInterface;

function button_block_node_view(array &$build, \Drupal\node\NodeInterface $node) {
  if ($node->getType() === 'product') {
    
    $build['add_to_cart_button'] = [
      '#type' => 'link',
      '#title' => t('Add to Cart'),
      '#url' => \Drupal\Core\Url::fromRoute('button_block.add_to_cart', ['node' => $node->id()]),
      '#attributes' => ['class' => ['button', 'add-to-cart-button']],
    ];
    
    $build['buy_now_button'] = [
      '#type' => 'link',
      '#title' => t('Buy Now'),
      '#url' => \Drupal\Core\Url::fromRoute('button_block.buy_now', ['node' => $node->id()]),
      '#attributes' => ['class' => ['button', 'buy-now-button']],
    ];
  }
}


/**
 * Implements hook_theme().
 */
function button_block_theme($existing, $type, $theme, $path) {
    return [
      'buy_dashboard' => [
        'variables' => [
          'rows' => [],
        ],
      ],
    ];
}